src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;


    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="relation")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="posts")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post")
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }



    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;


use App\Entity\Comment;
use App\Entity\Post;
use App\Form\AddCommentsType;
use App\Repository\CategoryRepository;
use App\Repository\PostRepository;
use ArrayObject;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("post", name="post")
 */
class PostController extends AbstractController
{
    /**
     *
     * @Route(path="/detail/{id}", requirements={"id"="\d+"}, name="_detail",methods={"GET","POST"}, defaults={1})
     */
    public function getDetailPost(PostRepository $postRepository, EntityManagerInterface $entityManager, int $id, Post $post, Request $request, CategoryRepository $categoryRepository)
    {
        $postDetail = $postRepository->find($id);

        if (is_null($postDetail)) {
            throw $this->createNotFoundException();
        }
        if ($id < 1) {
            throw $this->createNotFoundException();
        }


        //Autres post du meme auteur
        $othersPostSimilaryAuthor = $postRepository->findAllSimilaryAuthor($postDetail->getAuthor()->getId(), $id);//respecter l ordre


        // A voir si je creer une methode  pr la creation  d'un commentaire pour un 1 post //instanciation du formulaire ds le controller
        $comment = new Comment();
        $comment->setPost($post);
        $comment->setCreatedAt(new \DateTime());
        $commentForm = $this->createForm(AddCommentsType::class, $comment);

        // on peut faire : $commentForm = $this ->createForm(AddCommentsType::class, $comment)->handleRequest($request);
        //traitement du formulaire prends les données et injecte les ds $comment, $request -> de http fondation
        $commentForm->handleRequest($request);


        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            // donner des valeurs sur les champs non renseigne ds le form
            $comment->setPost($post);   //recuperer l id du post
            $entityManager->persist($comment);
            $entityManager->flush();
            $this->addFlash('succes', 'Commentaire ajouté!');
            return $this->redirectToRoute('post_detail', ['id' => $post->getId()]);
        }


        //Category
        $categoriesMostPost = $categoryRepository->findAll();
        $arrayObjects = new ArrayObject($categoriesMostPost);
        $arrayObjects->uasort(
            function($categoryA, $categoryB)
            {
                if (count($categoryA->getRelation()) == count($categoryB->getRelation())) {
                    return 0;
                }
                return count($categoryA->getRelation()) < count($categoryB->getRelation()) ? 1 : -1;
            }
        );
        // si on ne rentre pas ds le if on redirige
        return $this->render('post/detail_post.html.twig',
            [
                "postDetail" => $postDetail,
                "commentForm" => $commentForm->createView(),
                "othersPostAuthor" => $othersPostSimilaryAuthor,
                "categories" => $arrayObjects
            ]);


    }




}

templates/post/detail_post.html.twig
{% extends 'base.html.twig' %}



   {% block navigation %}
       <nav class="categoriesNavigation">
           <div class="container">
               <ul>
                   <li class="hoverExtend "><a href="{{ path('home') }}" title="home">Home</a></li>
                   {% for categorie in categories %}
                       <li class="hoverExtend
                           {% if categorie.name ==  postDetail.category.name %}
                                active
                           {% endif %}
                       ">
                           <a title="#">{{ categorie.name }}</a></li>
                   {% endfor %}
               </ul>
           </div>
       </nav>
   {% endblock %}
    {% block title %}
        {{ postDetail.title }} | {{ parent() }}
    {% endblock %}

    {% block body %}
        <section>
            <article class="article articleDetail">

                <div class="box">
                    <h3 class="title">{{ postDetail.title }}</h3>
                    <div class="info">
                        <div>
                            <span class="date">{{ postDetail.createdat | date("m/d/Y") }} <span
                                        data-current-year></span></span>
                        </div>
                        <div>by <a href="#"
                                   title="#">{{ postDetail.author.firstname ~" " ~ postDetail.author.lastname }}</a>
                        </div>
                        <div>in <a href="#" title="#">{{ postDetail.category.name }}</a></div>
                    </div>
                    <div class="rte js-imagelightbox">
                        <p class="drop-cap-1">
                            {{ postDetail.content |nl2br }}
                        </p>
                    </div>
                    <footer class="footer">
                        <div class="row">
                            <div class="col-sm-12 col-lg-6 moreInfo">
                                <div><span><i class="fa fa-comments"></i> {{ postDetail.comments | length }}    </span>
                                    Comments
                                </div>
                            </div>
                        </div>
                    </footer>
                </div>
            </article>
        </section>

        <section class="section_comments_detailPost">
            {# todo  css faire un display pour mettre cote a cote #}
            <!-- Comment -->
            <div class="list_Comments_postDetails">
                {% for listComments in  postDetail.comments %}
                    <div class="articleCommentsListing">
                        <div class="box">
                            <header>
                                <div class="row">
                                    <div class="col-xs-12 col-lg-8 commentInfo">
                                        <span class="name">{{ listComments.nickname }} </span>
                                        <span class="time info">le  {{ listComments.createdAt | date("d/m/Y") }}</span>
                                    </div>
                                </div>
                            </header>
                            <div class="c">
                                <p> {{ listComments.content }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {# Todo faire la mise en forme des commentaires #}
            <div class="articleComments box">
                <div class="row">
                    {{ form_start(commentForm) }}{# //bal ise d ouverture du formulaire = form #}

                    <h2>Comments</h2>
                    <div>
                        <div class="col-xs-12 col-sm-4 i">
                            {{ form_widget(commentForm.nickname,{'attr':
                                {
                                    'placeholder':'pseudo...',
                                    'class':'input'
                                }
                            }) }}
                        </div>
                        <div class="col-xs-12 col-sm-4 i">
                            {{ form_widget(commentForm.content,{'attr':{'placeholder':'commentaire...','class':'input'}}) }}
                        </div>
                        <div class="col-xs-12">
                            <div class="btns">
                                <button class="btn btn-color-full submit">
                                    <span>Add Comment</span>
                                </button>
                            </div>
                        </div>
                    </div>
                    {{ form_end(commentForm) }}
                </div>
            </div>
        </section>
    {% endblock %}


  {% block aside %}
      <aside class="col-xs-12 col-sm-4 aside">
          <div class="row">
              <!-- Our authors -->
              <div class="col-xs-12 i">
                  <div class="box ourAuthorsBox">
                      <h2>L'auteur</h2>

                      <div class="c">
                          <div>
                              <div class="i">
                                  <div class="name">{{ postDetail.author.firstname ~" "~postDetail.author.lastname }}</div>
                                  <p class="info">{{ postDetail.author.description }}</p>
                              </div>
                          </div>
                          <div class="btns">
                              <a href="page-about-us.html" title="#" class="btn btn-color-full"><span>Message</span></a>
                          </div>
                      </div>
                  </div>
              </div>

              <div class="col-xs-12 i">
                  <div class="box categories">
                      <h2>Autres Post du meme auteur</h2>
                      <div class="c">
                          <div class="i">
                              {% for p in othersPostAuthor %}
                                  <a href="{{ path('post_detail',{'id': p.id, 'author': p.author}) }}">
                                      <div><br>{{ p.title | upper }}</div>
                                  </a>
                              {% endfor %}
                          </div>
                      </div>
                      <div class="tab-content bordered"></div>

                  </div>
              </div>
          </div>
      </aside>


  {% endblock %}